export const categories = {
  HISTORY: "HISTORIA",
  CULTURE: "CULTURA",
  SPORTS: "DEPORTES",
  GEOGRAPHY: "GEOGRAFIA",
  TECHNOLOGY: "TECNOLOGIA",
  ENTERTAINMENT: "ENTRETENIMIENTO",
  SCIENCE: "CIENCIA",
  WINNER: "GANADOR",
};

export const RoomStatusEnum = {
  WAITING_USERS: "WAITING_USERS",
  PLAYING: "PLAYING",
  FINISHED: "FINISHED",
};

export const UserStatusEnum = {
  WAITING: "WAITING",
  ANSWERING: "ANSWERING",
  WINNER: "WINNER",
};

export const QuestionsTypeEnum = {
  BOOLEAN: "BOOLEAN",
  NUMERIC: "NUMERIC",
};
